
void    GTEWriteData0 (u_long value);
void    GTEWriteData1 (u_long value);
void    GTEWriteData2 (u_long value);
void    GTEWriteData3 (u_long value);
void    GTEWriteData4 (u_long value);
void    GTEWriteData5 (u_long value);
void    GTEWriteData6 (u_long value);
void    GTEWriteData7 (u_long value);
void    GTEWriteData8 (u_long value);
void    GTEWriteData9 (u_long value);
void    GTEWriteData10 (u_long value);
void    GTEWriteData11 (u_long value);
void    GTEWriteData12 (u_long value);
void    GTEWriteData13 (u_long value);
void    GTEWriteData14 (u_long value);
void    GTEWriteData15 (u_long value);
void    GTEWriteData16 (u_long value);
void    GTEWriteData17 (u_long value);
void    GTEWriteData18 (u_long value);
void    GTEWriteData19 (u_long value);
void    GTEWriteData20 (u_long value);
void    GTEWriteData21 (u_long value);
void    GTEWriteData22 (u_long value);
void    GTEWriteData23 (u_long value);
void    GTEWriteData24 (u_long value);
void    GTEWriteData25 (u_long value);
void    GTEWriteData26 (u_long value);
void    GTEWriteData27 (u_long value);
void    GTEWriteData28 (u_long value);
void    GTEWriteData29 (u_long value);
void    GTEWriteData30 (u_long value);
void    GTEWriteData31 (u_long value);

u_long  GTEReadData0 (void);
u_long  GTEReadData1 (void);
u_long  GTEReadData2 (void);
u_long  GTEReadData3 (void);
u_long  GTEReadData4 (void);
u_long  GTEReadData5 (void);
u_long  GTEReadData6 (void);
u_long  GTEReadData7 (void);
u_long  GTEReadData8 (void);
u_long  GTEReadData9 (void);
u_long  GTEReadData10 (void);
u_long  GTEReadData11 (void);
u_long  GTEReadData12 (void);
u_long  GTEReadData13 (void);
u_long  GTEReadData14 (void);
u_long  GTEReadData15 (void);
u_long  GTEReadData16 (void);
u_long  GTEReadData17 (void);
u_long  GTEReadData18 (void);
u_long  GTEReadData19 (void);
u_long  GTEReadData20 (void);
u_long  GTEReadData21 (void);
u_long  GTEReadData22 (void);
u_long  GTEReadData23 (void);
u_long  GTEReadData24 (void);
u_long  GTEReadData25 (void);
u_long  GTEReadData26 (void);
u_long  GTEReadData27 (void);
u_long  GTEReadData28 (void);
u_long  GTEReadData29 (void);
u_long  GTEReadData30 (void);
u_long  GTEReadData31 (void);

void    GTEWriteCtrl0 (u_long value);
void    GTEWriteCtrl1 (u_long value);
void    GTEWriteCtrl2 (u_long value);
void    GTEWriteCtrl3 (u_long value);
void    GTEWriteCtrl4 (u_long value);
void    GTEWriteCtrl5 (u_long value);
void    GTEWriteCtrl6 (u_long value);
void    GTEWriteCtrl7 (u_long value);
void    GTEWriteCtrl8 (u_long value);
void    GTEWriteCtrl9 (u_long value);
void    GTEWriteCtrl10 (u_long value);
void    GTEWriteCtrl11 (u_long value);
void    GTEWriteCtrl12 (u_long value);
void    GTEWriteCtrl13 (u_long value);
void    GTEWriteCtrl14 (u_long value);
void    GTEWriteCtrl15 (u_long value);
void    GTEWriteCtrl16 (u_long value);
void    GTEWriteCtrl17 (u_long value);
void    GTEWriteCtrl18 (u_long value);
void    GTEWriteCtrl19 (u_long value);
void    GTEWriteCtrl20 (u_long value);
void    GTEWriteCtrl21 (u_long value);
void    GTEWriteCtrl22 (u_long value);
void    GTEWriteCtrl23 (u_long value);
void    GTEWriteCtrl24 (u_long value);
void    GTEWriteCtrl25 (u_long value);
void    GTEWriteCtrl26 (u_long value);
void    GTEWriteCtrl27 (u_long value);
void    GTEWriteCtrl28 (u_long value);
void    GTEWriteCtrl29 (u_long value);
void    GTEWriteCtrl30 (u_long value);
void    GTEWriteCtrl31 (u_long value);

u_long  GTEReadCtrl0 (void);
u_long  GTEReadCtrl1 (void);
u_long  GTEReadCtrl2 (void);
u_long  GTEReadCtrl3 (void);
u_long  GTEReadCtrl4 (void);
u_long  GTEReadCtrl5 (void);
u_long  GTEReadCtrl6 (void);
u_long  GTEReadCtrl7 (void);
u_long  GTEReadCtrl8 (void);
u_long  GTEReadCtrl9 (void);
u_long  GTEReadCtrl10 (void);
u_long  GTEReadCtrl11 (void);
u_long  GTEReadCtrl12 (void);
u_long  GTEReadCtrl13 (void);
u_long  GTEReadCtrl14 (void);
u_long  GTEReadCtrl15 (void);
u_long  GTEReadCtrl16 (void);
u_long  GTEReadCtrl17 (void);
u_long  GTEReadCtrl18 (void);
u_long  GTEReadCtrl19 (void);
u_long  GTEReadCtrl20 (void);
u_long  GTEReadCtrl21 (void);
u_long  GTEReadCtrl22 (void);
u_long  GTEReadCtrl23 (void);
u_long  GTEReadCtrl24 (void);
u_long  GTEReadCtrl25 (void);
u_long  GTEReadCtrl26 (void);
u_long  GTEReadCtrl27 (void);
u_long  GTEReadCtrl28 (void);
u_long  GTEReadCtrl29 (void);
u_long  GTEReadCtrl30 (void);
u_long  GTEReadCtrl31 (void);

void    GTE_AVSZ3 (void);
